version: '3.8'
services:
  frontend:
    image: node:16-alpine
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npm install && npm start"
    environment:
      - CHOKIDAR_USEPOLLING=true